### ISSUE TITLE
httpd.* services and pfqueue are not able to start

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5035]
Due to change introduced by https://github.com/inverse-inc/packetfence/commit/27e7810305f6d82f67a7d29535431b406e0bfb44, `httpd.aaa`, `httpd.admin`, `httpd.webservices` and `pfqueue` are not able to start.

In logs:
```
Jan  9 06:02:08 pfcen7night httpd: Global symbol "$calling_station_id" requires explicit package name at /usr/local/pf/lib/pf/api.pm line 1377.\nGlobal symbol "$calling_station_id" requires explicit package name at /usr/local/pf/lib/pf/api.pm line 1379.\nGlobal symbol "$calling_station_id" requires explicit package name at /usr/local/pf/lib/pf/api.pm line 1382.\nBEGIN not safe after errors--compilation aborted at /usr/local/pf/lib/pf/api.pm line 1392.\nCompilation failed in require at /usr/local/pf/lib/pf/WebAPI.pm line 18.\nBEGIN failed--compilation aborted at /usr/local/pf/lib/pf/WebAPI.pm line 18.\nCompilation failed in require at (eval 2378) line 2.\n
```
