### ISSUE TITLE
v8.3 to v9: unable to display sources after an upgrade

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4547]
**Describe the bug**
After an upgrade from v8.3 to v9 (CentOS 7), Authentication sources and Security Events aren't display.

**To Reproduce**
1. Go to 'Configuration -> Policies and Access Control -> Authentication sources' or 'Configuration -> Compliance -> Security Events'

**Expected behavior**
Authentication sources and security events should appear.

**Additional context**

`packetfence.log` when going to Authentication sources menu:
```
May 20 15:36:36 nac packetfence: ERROR pfperl-api(26632): Attempt to reload pf/enforcement.pm aborted. 
Compilation failed in require at /usr/local/pf/lib/pf/web.pm line 57.                                                                                                                                      
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/web.pm line 57.                                                                                                                                 
Compilation failed in require at /usr/local/pf/lib/pf/web/util.pm line 28.                                                                                                                                 
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/web/util.pm line 28.                                                                                                                             
Compilation failed in require at /usr/local/pf/lib/pfappserver/Base/Form/Authentication/Action.pm line 25.
BEGIN failed--compilation aborted at /usr/local/pf/lib/pfappserver/Base/Form/Authentication/Action.pm line 25. 
Compilation failed in require at /usr/local/pf/lib/pfappserver/Form/Config/Source.pm line 24.                                                                                                             
BEGIN failed--compilation aborted at /usr/local/pf/lib/pfappserver/Form/Config/Source.pm line 24. 
Compilation failed in require at /usr/local/pf/lib/pf/UnifiedApi/Controller/Config/Sources.pm line 26
BEGIN failed--compilation aborted at /usr/local/pf/lib/pf/UnifiedApi/Controller/Config/Sources.pm line 26
Compilation failed in require at (eval 2919) line 1.                                                  
 (Mojolicious::Plugin::DefaultHelpers::_development) 
May 20 15:36:36 nac pfhttpd: api-frontend-access 127.0.0.1 - - [20/May/2019:15:36:36 +0200] "GET /api/v1/config/sources?sort=id&fields=id,description,type,class HTTP/1.1" 500 77 
May 20 15:36:36 nac httpd_admin_access: 10.1.90.11 - - [20/May/2019:15:36:35 +0200] "GET /api/v1/config/sources?sort=id&fields=id,description,type,class HTTP/1.1" 500 371 605 683026
```

`packetfence.log` when going to Security Events menu:
```
May 20 15:36:43 nac packetfence: ERROR pfperl-api(26631): Can't call method "new" on an undefined value at /usr/local/pf/lib/pf/UnifiedApi/Controller/Config.pm line 201.                                 
 (Mojolicious::Plugin::DefaultHelpers::_development)
```
After these two errors, I got only latest error when going in each menu.

**Comment by nqb** [comment]
Doing a `pfcmd pfconfig reload` didn't help.

**Comment by julsemaan** [comment]
Did you do a fixpermission after the upgrade?

This looks like the config files can't be read at all which is usually because of invalid permissions or owner/group

**Comment by nqb** [comment]
> Did you do a fixpermission after the upgrade?

Yes.

**Comment by julsemaan** [comment]
And are the permissions correct on the configuration files that are involved ?

(authentication.conf, security_events.conf)

**Comment by nqb** [comment]
Yes, looks good:
```
# ls -rtl /usr/local/pf/conf/security_events.conf
-rw-rw-r-- 1 pf pf 460 Mar 29 11:30 /usr/local/pf/conf/security_events.conf

# ls -rtl /usr/local/pf/conf/authentication.conf
-rw-rw-r-- 1 pf pf 5903 May 20 16:31 /usr/local/pf/conf/authentication.conf
```
Issue has been caused by the upgrade.

**Comment by nqb** [comment]
@julsemaan: it look like issue is not limited to Authentication Sources and Security Events, now I got following error message  when I go in Nodes or Users menu
```
May 21 15:51:12 nac packetfence: ERROR pfperl-api(26633): Can't call method "get_meta" on an undefined value at /usr/local/pf/lib/pf/UnifiedApi/Search/Builder.pm line 359.                                │
 (Mojolicious::Plugin::DefaultHelpers::_development) 
```

**Comment by jrouzierinverse** [comment]
This is a devious bug.
It seems to be depends on the order in which the modules are loaded.
Or maybe a module failed to load.
So I will preload all controllers to avoid this issue

**Comment by nqb** [comment]
@jrouzierinverse: I got my idea on this.

Log of the upgrade display following error:
```
2620 Can't locate object method "new" via package "pfconfig::namespaces::FilterEngine::Violation" at /usr/local/pf/lib/pfconfig/manager.pm line 94.
```

I wonder if it is not the root cause of this issue.

**Comment by nqb** [comment]
Because `pfconfig::namespaces::FilterEngine::Violation` doesn't exist anymore (moved to `SecurityEvent`).

**Comment by jrouzierinverse** [comment]
Then the issue more clear now pfconfig was never restarted

**Comment by jrouzierinverse** [comment]
Since pfconfig was never restarted some modules could not load properly.
Which caused any dependent modules to either partially load or complete fail to load.
Since the upgrade process was not followed I am closing this issue.
Reopen if you find that restarting pfconfig and pfperl-api does not solve the problem.

**Comment by nqb** [comment]
I didn't mention previously but, of course, I followed UPGRADE guide and I restarted packetfence-config.

**Comment by nqb** [comment]
Restart of `pfperl-api` has fixed issue. It looks like `packetfence-pfperl-api` has not been restarted by a `pfcmd service pf restart` I did at the end of the upgrade.
